spring:
  # Database config
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:multiplex
    username: sa
    password:
      driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  # Datetime format
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

# Constant values
const:
  seat:
    forbiddenEmptySpaceBetween: 1
  reservation:
    minTimeBeforeInMinutes: 15